# Generated by Django 4.1.2 on 2022-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="ip",
            field=models.CharField(default="127.0.0.1", max_length=100),
        ),
    ]
